name: Update README

on:
  schedule:
    - cron: '0 */72 * * *' # Cada 12 horas

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update README with recent activity
        uses: KevinAlexandro/KevinAlexandro@main # Reemplaza con tu información
