name: Update README

on:
  schedule:
    - cron: '0 */72 * * *' # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: GitHub - Activity - Readme
      # You may pin to the exact commit or the version.
      # uses: jamesgeorge007/github-activity-readme@df57d5cab9b53277241f93190e176b38dd95eb1a
        uses: KevinAlexandro/KevinAlexandro@main
          
